/* tslint:disable */
/* eslint-disable */
/**
 * 法令APIプロトタイプ
 * 法令データを取得・検索するAPIです。  * 必ずデジタル庁の<a href=\"https://www.digital.go.jp/policies/legal-practice/public-test\" target=\"_blank\">法令APIプロトタイプ公開テストのページ</a>をご確認頂き、利用規約に同意頂いた上でご利用ください。  * 本プロトタイプは、一時的な試験提供ですので、実際のシステムへの組み込み等についてはお控えください。実際のサービス提供への活用を頂くには、正式提供している<a href=\"https://elaws.e-gov.go.jp/apitop/\" target=\"_blank\">現行の法令API</a>、もしくは今後検討している高度化後の法令APIをご利用頂く必要があることにご留意ください。  * 使用するデータは、テスト用データのため、一部含まれない法令や、法令標準XMLスキーマには無い属性や項目が含まれていることがあります。  * 本環境はサーバーメンテナンスを行うことがあり、メンテナンス中はご利用がいただけない事があります。長期間の停止を伴うサーバーメンテナンスを行う際はデジタル庁HPでお知らせ致します。また、API仕様についても、公開テスト期間中に変更される可能性がありますので、ご了承ください。 
 *
 * The version of the OpenAPI document: 2.1.77
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoryCd,
  Era,
  ErrorInfo,
  KeywordResponse,
  LawRevisionsResponse,
  LawType,
  LawdataResponse,
  LawsResponse,
  Mission,
  OrderNo,
  RepealStatus,
  ResponseFormat,
  Status,
} from '../models/index';
import {
    CategoryCdFromJSON,
    CategoryCdToJSON,
    EraFromJSON,
    EraToJSON,
    ErrorInfoFromJSON,
    ErrorInfoToJSON,
    KeywordResponseFromJSON,
    KeywordResponseToJSON,
    LawRevisionsResponseFromJSON,
    LawRevisionsResponseToJSON,
    LawTypeFromJSON,
    LawTypeToJSON,
    LawdataResponseFromJSON,
    LawdataResponseToJSON,
    LawsResponseFromJSON,
    LawsResponseToJSON,
    MissionFromJSON,
    MissionToJSON,
    OrderNoFromJSON,
    OrderNoToJSON,
    RepealStatusFromJSON,
    RepealStatusToJSON,
    ResponseFormatFromJSON,
    ResponseFormatToJSON,
    StatusFromJSON,
    StatusToJSON,
} from '../models/index';

export interface GetAttachedRequest {
    lawRevisionId: string;
    src?: string;
}

export interface GetKeywordRequest {
    keyword: string;
    lawType?: Array<LawType>;
    promulgationDateFrom?: Date;
    promulgationDateTo?: Date;
    asof?: Date;
    lawNum?: string;
    lawNumEra?: Era;
    lawNumYear?: number;
    lawNumType?: LawType;
    lawNumNum?: string;
    categoryCd?: Array<CategoryCd>;
    order?: Array<string>;
    orderNo?: OrderNo;
    limit?: number;
    offset?: number;
    responseFormat?: ResponseFormat | null;
}

export interface GetLawdataRequest {
    lawId?: string;
    lawNum?: string;
    asof?: Date;
    elm?: string;
    omitLawFullText?: boolean;
    omitAmendmentSupplProvision?: boolean;
    includeAttachedFileContent?: boolean;
    responseFormat?: ResponseFormat | null;
}

export interface GetLawlistRequest {
    asof?: Date;
    lawId?: string;
    lawNum?: string;
    lawNumEra?: Era;
    lawNumYear?: number;
    lawNumType?: LawType;
    lawNumNum?: string;
    promulgationDateFrom?: Date;
    promulgationDateTo?: Date;
    lawType?: Array<LawType>;
    lawTitle?: string;
    lawTitleKana?: string;
    lawTitleKanaseion?: string;
    amendmentDateFrom?: Date;
    amendmentDateTo?: Date;
    amendmentPromulgateDateFrom?: Date;
    amendmentPromulgateDateTo?: Date;
    amendmentLawId?: string;
    amendmentLawTitle?: string;
    amendmentLawTitleKana?: string;
    amendmentLawTitleKanaseion?: string;
    amendmentLawNum?: string;
    updatedFrom?: Date;
    updatedTo?: Date;
    repealStatus?: Array<RepealStatus>;
    repealDateFrom?: Date;
    repealDateTo?: Date;
    remainInForce?: boolean;
    categoryCd?: Array<CategoryCd>;
    mission?: Array<Mission>;
    status?: Array<Status>;
    omitCurrentRevisionInfo?: boolean;
    order?: Array<string>;
    orderNo?: OrderNo;
    limit?: number;
    offset?: number;
    responseFormat?: ResponseFormat | null;
}

export interface GetRevisionsRequest {
    lawId?: string;
    lawNum?: string;
    lawTitle?: string;
    lawTitleKana?: string;
    lawTitleKanaseion?: string;
    amendmentDateFrom?: Date;
    amendmentDateTo?: Date;
    amendmentPromulgateDateFrom?: Date;
    amendmentPromulgateDateTo?: Date;
    amendmentLawId?: string;
    amendmentLawTitle?: string;
    amendmentLawTitleKana?: string;
    amendmentLawTitleKanaseion?: string;
    amendmentLawNum?: string;
    updatedFrom?: Date;
    updatedTo?: Date;
    repealStatus?: Array<RepealStatus>;
    repealDateFrom?: Date;
    repealDateTo?: Date;
    remainInForce?: boolean;
    categoryCd?: Array<CategoryCd>;
    mission?: Array<Mission>;
    status?: Array<Status>;
    responseFormat?: ResponseFormat | null;
}

/**
 * 
 */
export class LawsApiApi extends runtime.BaseAPI {

    /**
     * 法令の添付ファイルを取得します。  指定した法令履歴IDに該当する法令の添付ファイルを指定することで、バイナリデータを取得できます。  ファイルを指定しない場合は、当該法令の全ての添付ファイルを pict フォルダに格納してZIP圧縮したバイナリデータを取得できます。 
     * 添付ファイル取得API
     */
    async getAttachedRaw(requestParameters: GetAttachedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.lawRevisionId === null || requestParameters.lawRevisionId === undefined) {
            throw new runtime.RequiredError('lawRevisionId','Required parameter requestParameters.lawRevisionId was null or undefined when calling getAttached.');
        }

        const queryParameters: any = {};

        if (requestParameters.lawRevisionId !== undefined) {
            queryParameters['law_revision_id'] = requestParameters.lawRevisionId;
        }

        if (requestParameters.src !== undefined) {
            queryParameters['src'] = requestParameters.src;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/attached`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 法令の添付ファイルを取得します。  指定した法令履歴IDに該当する法令の添付ファイルを指定することで、バイナリデータを取得できます。  ファイルを指定しない場合は、当該法令の全ての添付ファイルを pict フォルダに格納してZIP圧縮したバイナリデータを取得できます。 
     * 添付ファイル取得API
     */
    async getAttached(requestParameters: GetAttachedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getAttachedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 指定したキーワードを本文に含む法令の一覧を取得します。 指定した条件に該当する複数の法令をレスポンスの `items` に格納します。  また、それぞれの法令について、下記の情報を格納します。  * `law_info` - 改正履歴に依存しない法令情報を格納します。法令番号など、改正されない情報が該当します。法令名は改正されることがありますので、改正履歴に依存する法令情報（`revision_info`）に格納されます。 * `revision_info` - 改正履歴に依存する法令情報（改正されうる情報や、改正時点に関する情報）について、指定した条件に合致する一つの改正履歴の情報を格納します。 `asof` などを指定しない場合は現時点で最新の改正履歴、 `asof` を指定した場合はその時点で最新の改正履歴を格納します。 * `sentence` - 版の段落内本文を格納します。  パラメータの多くは、 <a href=\"#model-keyword_response\">keyword_response</a> に定義されているレスポンス中、 `items` の各要素の `law_info` または `revision_info` の同名のプロパティに対応します（例えば、 `law_num` や `law_title` など）。パラメータを指定することで、これらのプロパティの値を対象にフィルタを行い、 `items` に格納する法令や、検索対象の改正履歴を選択するように動作します。 
     * キーワード検索API
     */
    async getKeywordRaw(requestParameters: GetKeywordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeywordResponse>> {
        if (requestParameters.keyword === null || requestParameters.keyword === undefined) {
            throw new runtime.RequiredError('keyword','Required parameter requestParameters.keyword was null or undefined when calling getKeyword.');
        }

        const queryParameters: any = {};

        if (requestParameters.keyword !== undefined) {
            queryParameters['keyword'] = requestParameters.keyword;
        }

        if (requestParameters.lawType) {
            queryParameters['law_type'] = requestParameters.lawType.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.promulgationDateFrom !== undefined) {
            queryParameters['promulgation_date_from'] = (requestParameters.promulgationDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.promulgationDateTo !== undefined) {
            queryParameters['promulgation_date_to'] = (requestParameters.promulgationDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.asof !== undefined) {
            queryParameters['asof'] = (requestParameters.asof as any).toISOString().substring(0,10);
        }

        if (requestParameters.lawNum !== undefined) {
            queryParameters['law_num'] = requestParameters.lawNum;
        }

        if (requestParameters.lawNumEra !== undefined) {
            queryParameters['law_num_era'] = requestParameters.lawNumEra;
        }

        if (requestParameters.lawNumYear !== undefined) {
            queryParameters['law_num_year'] = requestParameters.lawNumYear;
        }

        if (requestParameters.lawNumType !== undefined) {
            queryParameters['law_num_type'] = requestParameters.lawNumType;
        }

        if (requestParameters.lawNumNum !== undefined) {
            queryParameters['law_num_num'] = requestParameters.lawNumNum;
        }

        if (requestParameters.categoryCd) {
            queryParameters['category_cd'] = requestParameters.categoryCd.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.order) {
            queryParameters['order'] = requestParameters.order.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.orderNo !== undefined) {
            queryParameters['order_no'] = requestParameters.orderNo;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.responseFormat !== undefined) {
            queryParameters['response_format'] = requestParameters.responseFormat;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/keyword`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeywordResponseFromJSON(jsonValue));
    }

    /**
     * 指定したキーワードを本文に含む法令の一覧を取得します。 指定した条件に該当する複数の法令をレスポンスの `items` に格納します。  また、それぞれの法令について、下記の情報を格納します。  * `law_info` - 改正履歴に依存しない法令情報を格納します。法令番号など、改正されない情報が該当します。法令名は改正されることがありますので、改正履歴に依存する法令情報（`revision_info`）に格納されます。 * `revision_info` - 改正履歴に依存する法令情報（改正されうる情報や、改正時点に関する情報）について、指定した条件に合致する一つの改正履歴の情報を格納します。 `asof` などを指定しない場合は現時点で最新の改正履歴、 `asof` を指定した場合はその時点で最新の改正履歴を格納します。 * `sentence` - 版の段落内本文を格納します。  パラメータの多くは、 <a href=\"#model-keyword_response\">keyword_response</a> に定義されているレスポンス中、 `items` の各要素の `law_info` または `revision_info` の同名のプロパティに対応します（例えば、 `law_num` や `law_title` など）。パラメータを指定することで、これらのプロパティの値を対象にフィルタを行い、 `items` に格納する法令や、検索対象の改正履歴を選択するように動作します。 
     * キーワード検索API
     */
    async getKeyword(requestParameters: GetKeywordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeywordResponse> {
        const response = await this.getKeywordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 法令の本文を取得します。 指定した条件に該当する1つの法令について、本文をレスポンスの `law_full_text` に格納します。  また、下記の情報を格納します。  * `law_info` - 改正履歴に依存しない法令情報を格納します。法令番号など、改正されない情報が該当します。法令名は改正されることがありますので、改正履歴に依存する法令情報（`revision_info`）に格納されます。 * `revision_info` - 改正履歴に依存する法令情報（改正されうる情報や、改正時点に関する情報）について、指定した条件に合致する一つの改正履歴の情報を格納します。 `asof` を指定しない場合は現時点で最新の改正履歴、 `asof` を指定した場合はその時点で最新の改正履歴を格納します。  `elm` パラメータを指定することで、本文中、条項など、一部を指定して取得することもできます。  `response_format`の指定によりAPIのレスポンス形式が\"xml\"または\"json\"に切り替わりますが、これに伴い`law_full_text`も以下のように変わります。<br/> * **\"xml\"**が指定された場合、法令標準XMLスキーマに準拠したXMLを格納します。<br/> * **\"json\"**が指定された場合、法令標準XMLと相互に変換可能なjson形式を格納します。<br/> このjson仕様は暫定的なものですが、法令標準XMLのタグ、属性、子要素がそれぞれ「tag」、「attr」、「children」に対応し、内容は法令標準XMLと同様となります。<br/>  <font size=\"1\"> <h3>法令標準XMLとJSONの対応表</h3> 法令標準XMLスキーマについては<a href=\"\">こちら</a>を参照してください。（リンク先については検討中のため遷移できません）<br/> 例）\\<Sentence Num=\"1\" WritingMode=\"vertical\">         この法律は、処分、行政指導及び届出に関する手続並びに命令等を定める手続に関し、・・・\\</Sentence> </font> <table bgcolor=\"white\" border=\"1\">   <tr bgcolor=\"#DDFFFF\">     <th width=\"10%\">項目名</th>     <th width=\"45%\">XML</th>     <th width=\"45%\">JSON</th>   </tr>   <tr>     <td>タグ</td>     <td>Sentence</td>     <td>\"tag\": \"Sentence\"</td>   </tr>   <tr>     <td>属性</td>     <td>Num=\"1\" WritingMode=\"vertical\"</td>     <td>\"attr\": {\"Num\": \"1\",\"WritingMode\": \"vertical\"}</td>     </tr>   <tr>     <td>子要素</td>     <td>この法律は、処分、行政指導及び届出に関する手続並びに命令等を定める手続に関し、・・・</td>     <td>\"children\": [\"この法律は、処分、行政指導及び届出に関する手続並びに命令等を定める手続に関し、・・・\"]</td>   </tr> </table> 
     * 法令本文取得API
     */
    async getLawdataRaw(requestParameters: GetLawdataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LawdataResponse>> {
        const queryParameters: any = {};

        if (requestParameters.lawId !== undefined) {
            queryParameters['law_id'] = requestParameters.lawId;
        }

        if (requestParameters.lawNum !== undefined) {
            queryParameters['law_num'] = requestParameters.lawNum;
        }

        if (requestParameters.asof !== undefined) {
            queryParameters['asof'] = (requestParameters.asof as any).toISOString().substring(0,10);
        }

        if (requestParameters.elm !== undefined) {
            queryParameters['elm'] = requestParameters.elm;
        }

        if (requestParameters.omitLawFullText !== undefined) {
            queryParameters['omit_law_full_text'] = requestParameters.omitLawFullText;
        }

        if (requestParameters.omitAmendmentSupplProvision !== undefined) {
            queryParameters['omit_amendment_suppl_provision'] = requestParameters.omitAmendmentSupplProvision;
        }

        if (requestParameters.includeAttachedFileContent !== undefined) {
            queryParameters['include_attached_file_content'] = requestParameters.includeAttachedFileContent;
        }

        if (requestParameters.responseFormat !== undefined) {
            queryParameters['response_format'] = requestParameters.responseFormat;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/lawdata`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LawdataResponseFromJSON(jsonValue));
    }

    /**
     * 法令の本文を取得します。 指定した条件に該当する1つの法令について、本文をレスポンスの `law_full_text` に格納します。  また、下記の情報を格納します。  * `law_info` - 改正履歴に依存しない法令情報を格納します。法令番号など、改正されない情報が該当します。法令名は改正されることがありますので、改正履歴に依存する法令情報（`revision_info`）に格納されます。 * `revision_info` - 改正履歴に依存する法令情報（改正されうる情報や、改正時点に関する情報）について、指定した条件に合致する一つの改正履歴の情報を格納します。 `asof` を指定しない場合は現時点で最新の改正履歴、 `asof` を指定した場合はその時点で最新の改正履歴を格納します。  `elm` パラメータを指定することで、本文中、条項など、一部を指定して取得することもできます。  `response_format`の指定によりAPIのレスポンス形式が\"xml\"または\"json\"に切り替わりますが、これに伴い`law_full_text`も以下のように変わります。<br/> * **\"xml\"**が指定された場合、法令標準XMLスキーマに準拠したXMLを格納します。<br/> * **\"json\"**が指定された場合、法令標準XMLと相互に変換可能なjson形式を格納します。<br/> このjson仕様は暫定的なものですが、法令標準XMLのタグ、属性、子要素がそれぞれ「tag」、「attr」、「children」に対応し、内容は法令標準XMLと同様となります。<br/>  <font size=\"1\"> <h3>法令標準XMLとJSONの対応表</h3> 法令標準XMLスキーマについては<a href=\"\">こちら</a>を参照してください。（リンク先については検討中のため遷移できません）<br/> 例）\\<Sentence Num=\"1\" WritingMode=\"vertical\">         この法律は、処分、行政指導及び届出に関する手続並びに命令等を定める手続に関し、・・・\\</Sentence> </font> <table bgcolor=\"white\" border=\"1\">   <tr bgcolor=\"#DDFFFF\">     <th width=\"10%\">項目名</th>     <th width=\"45%\">XML</th>     <th width=\"45%\">JSON</th>   </tr>   <tr>     <td>タグ</td>     <td>Sentence</td>     <td>\"tag\": \"Sentence\"</td>   </tr>   <tr>     <td>属性</td>     <td>Num=\"1\" WritingMode=\"vertical\"</td>     <td>\"attr\": {\"Num\": \"1\",\"WritingMode\": \"vertical\"}</td>     </tr>   <tr>     <td>子要素</td>     <td>この法律は、処分、行政指導及び届出に関する手続並びに命令等を定める手続に関し、・・・</td>     <td>\"children\": [\"この法律は、処分、行政指導及び届出に関する手続並びに命令等を定める手続に関し、・・・\"]</td>   </tr> </table> 
     * 法令本文取得API
     */
    async getLawdata(requestParameters: GetLawdataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LawdataResponse> {
        const response = await this.getLawdataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 法令の一覧を取得します。 指定した条件に該当する複数の法令をレスポンスの `laws` に格納します。  また、それぞれの法令について、下記の情報を格納します。  * `law_info` - 改正履歴に依存しない法令情報を格納します。法令番号など、改正されない情報が該当します。法令名は改正されることがありますので、改正履歴に依存する法令情報（`revision_info`や `current_revision_info`）に格納されます。 * `revision_info` - 改正履歴に依存する法令情報（改正されうる情報や、改正時点に関する情報）について、指定した条件に合致する一つの改正履歴の情報を格納します。 `asof` などを指定しない場合は現時点で最新の改正履歴、 `asof` を指定した場合はその時点で最新の改正履歴を格納します。 * `current_revision_info` - `asof` などの指定にかかわらず、現在以前の最後の改正履歴を格納します。  パラメータの多くは、 <a href=\"#model-lawdata_response\">lawdata_response</a> に定義されているレスポンス中、 `laws` の各要素の `law_info` または `revision_info` の同名のプロパティに対応します（例えば、 `law_num` や `law_title` など）。パラメータを指定することで、これらのプロパティの値を対象にフィルタを行い、 `laws` に格納する法令や、 `revision_info` に格納する改正履歴を選択するように動作します。 
     * 法令一覧取得API
     */
    async getLawlistRaw(requestParameters: GetLawlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LawsResponse>> {
        const queryParameters: any = {};

        if (requestParameters.asof !== undefined) {
            queryParameters['asof'] = (requestParameters.asof as any).toISOString().substring(0,10);
        }

        if (requestParameters.lawId !== undefined) {
            queryParameters['law_id'] = requestParameters.lawId;
        }

        if (requestParameters.lawNum !== undefined) {
            queryParameters['law_num'] = requestParameters.lawNum;
        }

        if (requestParameters.lawNumEra !== undefined) {
            queryParameters['law_num_era'] = requestParameters.lawNumEra;
        }

        if (requestParameters.lawNumYear !== undefined) {
            queryParameters['law_num_year'] = requestParameters.lawNumYear;
        }

        if (requestParameters.lawNumType !== undefined) {
            queryParameters['law_num_type'] = requestParameters.lawNumType;
        }

        if (requestParameters.lawNumNum !== undefined) {
            queryParameters['law_num_num'] = requestParameters.lawNumNum;
        }

        if (requestParameters.promulgationDateFrom !== undefined) {
            queryParameters['promulgation_date_from'] = (requestParameters.promulgationDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.promulgationDateTo !== undefined) {
            queryParameters['promulgation_date_to'] = (requestParameters.promulgationDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.lawType) {
            queryParameters['law_type'] = requestParameters.lawType.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.lawTitle !== undefined) {
            queryParameters['law_title'] = requestParameters.lawTitle;
        }

        if (requestParameters.lawTitleKana !== undefined) {
            queryParameters['law_title_kana'] = requestParameters.lawTitleKana;
        }

        if (requestParameters.lawTitleKanaseion !== undefined) {
            queryParameters['law_title_kanaseion'] = requestParameters.lawTitleKanaseion;
        }

        if (requestParameters.amendmentDateFrom !== undefined) {
            queryParameters['amendment_date_from'] = (requestParameters.amendmentDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentDateTo !== undefined) {
            queryParameters['amendment_date_to'] = (requestParameters.amendmentDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentPromulgateDateFrom !== undefined) {
            queryParameters['amendment_promulgate_date_from'] = (requestParameters.amendmentPromulgateDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentPromulgateDateTo !== undefined) {
            queryParameters['amendment_promulgate_date_to'] = (requestParameters.amendmentPromulgateDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentLawId !== undefined) {
            queryParameters['amendment_law_id'] = requestParameters.amendmentLawId;
        }

        if (requestParameters.amendmentLawTitle !== undefined) {
            queryParameters['amendment_law_title'] = requestParameters.amendmentLawTitle;
        }

        if (requestParameters.amendmentLawTitleKana !== undefined) {
            queryParameters['amendment_law_title_kana'] = requestParameters.amendmentLawTitleKana;
        }

        if (requestParameters.amendmentLawTitleKanaseion !== undefined) {
            queryParameters['amendment_law_title_kanaseion'] = requestParameters.amendmentLawTitleKanaseion;
        }

        if (requestParameters.amendmentLawNum !== undefined) {
            queryParameters['amendment_law_num'] = requestParameters.amendmentLawNum;
        }

        if (requestParameters.updatedFrom !== undefined) {
            queryParameters['updated_from'] = (requestParameters.updatedFrom as any).toISOString();
        }

        if (requestParameters.updatedTo !== undefined) {
            queryParameters['updated_to'] = (requestParameters.updatedTo as any).toISOString();
        }

        if (requestParameters.repealStatus) {
            queryParameters['repeal_status'] = requestParameters.repealStatus.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.repealDateFrom !== undefined) {
            queryParameters['repeal_date_from'] = (requestParameters.repealDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.repealDateTo !== undefined) {
            queryParameters['repeal_date_to'] = (requestParameters.repealDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.remainInForce !== undefined) {
            queryParameters['remain_in_force'] = requestParameters.remainInForce;
        }

        if (requestParameters.categoryCd) {
            queryParameters['category_cd'] = requestParameters.categoryCd.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.mission) {
            queryParameters['mission'] = requestParameters.mission.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.status) {
            queryParameters['status'] = requestParameters.status.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.omitCurrentRevisionInfo !== undefined) {
            queryParameters['omit_current_revision_info'] = requestParameters.omitCurrentRevisionInfo;
        }

        if (requestParameters.order) {
            queryParameters['order'] = requestParameters.order.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.orderNo !== undefined) {
            queryParameters['order_no'] = requestParameters.orderNo;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.responseFormat !== undefined) {
            queryParameters['response_format'] = requestParameters.responseFormat;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/laws`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LawsResponseFromJSON(jsonValue));
    }

    /**
     * 法令の一覧を取得します。 指定した条件に該当する複数の法令をレスポンスの `laws` に格納します。  また、それぞれの法令について、下記の情報を格納します。  * `law_info` - 改正履歴に依存しない法令情報を格納します。法令番号など、改正されない情報が該当します。法令名は改正されることがありますので、改正履歴に依存する法令情報（`revision_info`や `current_revision_info`）に格納されます。 * `revision_info` - 改正履歴に依存する法令情報（改正されうる情報や、改正時点に関する情報）について、指定した条件に合致する一つの改正履歴の情報を格納します。 `asof` などを指定しない場合は現時点で最新の改正履歴、 `asof` を指定した場合はその時点で最新の改正履歴を格納します。 * `current_revision_info` - `asof` などの指定にかかわらず、現在以前の最後の改正履歴を格納します。  パラメータの多くは、 <a href=\"#model-lawdata_response\">lawdata_response</a> に定義されているレスポンス中、 `laws` の各要素の `law_info` または `revision_info` の同名のプロパティに対応します（例えば、 `law_num` や `law_title` など）。パラメータを指定することで、これらのプロパティの値を対象にフィルタを行い、 `laws` に格納する法令や、 `revision_info` に格納する改正履歴を選択するように動作します。 
     * 法令一覧取得API
     */
    async getLawlist(requestParameters: GetLawlistRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LawsResponse> {
        const response = await this.getLawlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 法令の改正履歴の一覧を取得します。 指定した条件に該当する1つの法令について、改正履歴の一覧をレスポンスの `revisions` に格納します。  パラメータの多くは、 <a href=\"#model-law_revisions_response\">law_revisions_response</a> に定義されているレスポンス中、 `revisions` の各要素の同名のプロパティに対応します。パラメータを指定することで、これらのプロパティの値を対象にフィルタを行い、 `revisions` に格納する改正履歴を選択するように動作します。 
     * 法令履歴一覧取得API
     */
    async getRevisionsRaw(requestParameters: GetRevisionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LawRevisionsResponse>> {
        const queryParameters: any = {};

        if (requestParameters.lawId !== undefined) {
            queryParameters['law_id'] = requestParameters.lawId;
        }

        if (requestParameters.lawNum !== undefined) {
            queryParameters['law_num'] = requestParameters.lawNum;
        }

        if (requestParameters.lawTitle !== undefined) {
            queryParameters['law_title'] = requestParameters.lawTitle;
        }

        if (requestParameters.lawTitleKana !== undefined) {
            queryParameters['law_title_kana'] = requestParameters.lawTitleKana;
        }

        if (requestParameters.lawTitleKanaseion !== undefined) {
            queryParameters['law_title_kanaseion'] = requestParameters.lawTitleKanaseion;
        }

        if (requestParameters.amendmentDateFrom !== undefined) {
            queryParameters['amendment_date_from'] = (requestParameters.amendmentDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentDateTo !== undefined) {
            queryParameters['amendment_date_to'] = (requestParameters.amendmentDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentPromulgateDateFrom !== undefined) {
            queryParameters['amendment_promulgate_date_from'] = (requestParameters.amendmentPromulgateDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentPromulgateDateTo !== undefined) {
            queryParameters['amendment_promulgate_date_to'] = (requestParameters.amendmentPromulgateDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.amendmentLawId !== undefined) {
            queryParameters['amendment_law_id'] = requestParameters.amendmentLawId;
        }

        if (requestParameters.amendmentLawTitle !== undefined) {
            queryParameters['amendment_law_title'] = requestParameters.amendmentLawTitle;
        }

        if (requestParameters.amendmentLawTitleKana !== undefined) {
            queryParameters['amendment_law_title_kana'] = requestParameters.amendmentLawTitleKana;
        }

        if (requestParameters.amendmentLawTitleKanaseion !== undefined) {
            queryParameters['amendment_law_title_kanaseion'] = requestParameters.amendmentLawTitleKanaseion;
        }

        if (requestParameters.amendmentLawNum !== undefined) {
            queryParameters['amendment_law_num'] = requestParameters.amendmentLawNum;
        }

        if (requestParameters.updatedFrom !== undefined) {
            queryParameters['updated_from'] = (requestParameters.updatedFrom as any).toISOString();
        }

        if (requestParameters.updatedTo !== undefined) {
            queryParameters['updated_to'] = (requestParameters.updatedTo as any).toISOString();
        }

        if (requestParameters.repealStatus) {
            queryParameters['repeal_status'] = requestParameters.repealStatus.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.repealDateFrom !== undefined) {
            queryParameters['repeal_date_from'] = (requestParameters.repealDateFrom as any).toISOString().substring(0,10);
        }

        if (requestParameters.repealDateTo !== undefined) {
            queryParameters['repeal_date_to'] = (requestParameters.repealDateTo as any).toISOString().substring(0,10);
        }

        if (requestParameters.remainInForce !== undefined) {
            queryParameters['remain_in_force'] = requestParameters.remainInForce;
        }

        if (requestParameters.categoryCd) {
            queryParameters['category_cd'] = requestParameters.categoryCd.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.mission) {
            queryParameters['mission'] = requestParameters.mission.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.status) {
            queryParameters['status'] = requestParameters.status.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.responseFormat !== undefined) {
            queryParameters['response_format'] = requestParameters.responseFormat;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/law_revisions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LawRevisionsResponseFromJSON(jsonValue));
    }

    /**
     * 法令の改正履歴の一覧を取得します。 指定した条件に該当する1つの法令について、改正履歴の一覧をレスポンスの `revisions` に格納します。  パラメータの多くは、 <a href=\"#model-law_revisions_response\">law_revisions_response</a> に定義されているレスポンス中、 `revisions` の各要素の同名のプロパティに対応します。パラメータを指定することで、これらのプロパティの値を対象にフィルタを行い、 `revisions` に格納する改正履歴を選択するように動作します。 
     * 法令履歴一覧取得API
     */
    async getRevisions(requestParameters: GetRevisionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LawRevisionsResponse> {
        const response = await this.getRevisionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
